services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: reservas
      POSTGRES_PASSWORD: reservas
      POSTGRES_DB: reservasdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [postgres]

volumes:
  pgdata:
